### PR TITLE
Converted to java 8 with h2 database

### PR DESCRIPTION
**Pull request by TheToasterRoaster**

### CODE REVIEW

**Review by sophiagavrila — CHANGES_REQUESTED** [review]
@TheToasterRoaster This is a great start - could you please make the following changes:

- [x]  title this PR with the main changes made and add any necessary details about what this PR adds to main

- [x] Change the `application.properties` file to include connection properties to H2 database. (Talk with @JoshuaLeoSmith about this I believe he added those properly in his branch [here](https://github.com/Revature-CashOverflow-2/CashOverflow-spring/blob/Josh-refactor/src/main/resources/application.properties)

- [x] Ensure that the app reaches a build success.  Right now the tests in the backend are causing 27 errors.  You can find the failing build details [here](https://github.com/Revature-CashOverflow-2/CashOverflow-spring/runs/5880519289?check_suite_focus=true)

**Review by sophiagavrila — APPROVED** [review]
LGTM - awaiting other folks' approval.  We will forgo the security hotspot and merge it through

**Comment by sophiagavrila** [comment]
@TheToasterRoaster Could you also change the `server.port` to 5000 in the `application.properties` please?

Elastic Beanstalk expects it to be running on that port

**Review by sophiagavrila — APPROVED** [review]
LGTM

**Review by Dlcordle — APPROVED** [review]
LGTM

**Review by JoshuaLeoSmith — APPROVED** [review]

**Pull request merged**
